### ISSUE TITLE
your API does not work

### ISSUE THREAD

**Issue by AmirLayegh** [alibaba/EasyNLP#115]
It seems that your API does not work when I try to use the AutoTokenizer.frompretrained(), I face the error message which shows "raise Exception(f'{pretrained_model_name_or_path} is not a filer or folder.')"
I also tried the code which is included in your GitHub repository and again I received the same error message.

**Comment by AmirLayegh** [comment]
<img width="1144" alt="Screenshot 2022-06-08 at 20 49 28" src="https://user-images.githubusercontent.com/86609615/173844828-24508b46-8d71-4744-a37a-5670385adc58.png">
<img width="1347" alt="Screenshot 2022-06-08 at 20 48 43" src="https://user-images.githubusercontent.com/86609615/173844844-18004cf8-8be7-4e44-b1d5-c926dce3ed3a.png">

**Comment by chywang** [comment]
@ztl-35 Would you check this problem pls

**Comment by ztl-35** [comment]
hi, we test our text_classify API, it works well and you can try this script in **bert_classify** folder **run_train_eval_predict_appzoo_local.sh**. The results are shown as follows:
![image](https://user-images.githubusercontent.com/31171445/173982101-4e1cb1c5-4404-4c98-9254-92fba209cf50.png)
