### ISSUE TITLE
example [quick_start_user_defined] run too slow

### ISSUE THREAD

**Issue by nlp4zen** [alibaba/EasyNLP#139]
run a file : run_user_defined_local_cpu.sh in path: example/quick_start_user_defined, then run too slow after logging: 
========== Evaluation at global step 50 ==========

![image](https://user-images.githubusercontent.com/109053176/178180167-062979f4-f5c1-447f-89da-d4c21b4512fa.png)

my environment：
OS： Ubuntu20 in VMware Workstation
python： 3.6.13

install easynlp by : https://www.yuque.com/easyx/easynlp/tepd59

**Comment by chywang** [comment]
@ztl-35 would you check this demo to see whether there is a problem? cpu environment only
