### ISSUE TITLE
text2image的预训练模型，没有找到啊

### ISSUE THREAD

**Issue by Johnson-yue** [alibaba/EasyNLP#166]
hi, I don't find the "pai-painter-commercial-base-zh" or "pai/pai-painter-base-zh" or "alibaba-pai/pai-painter-large-zh" for text2image pretrained model weight

**Comment by chywang** [comment]
would you give a simple instruction on this @ttliu-kiwi

**Comment by ttliu-kiwi** [comment]
alibaba-pai/pai-painter-large-zh: 
`wget https://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/easynlp_modelzoo/alibaba-pai/pai-painter-large-zh.tgz`
alibaba-pai/pai-painter-base-zh:
`wget https://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/easynlp_modelzoo/alibaba-pai/pai-painter-base-zh.tgz`
pai-painter-commercial-base-zh:
`wget https://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/easynlp_modelzoo/alibaba-pai/pai-painter-commercial-base-zh.tgz`

**Comment by ttliu-kiwi** [comment]
> hi, I don't find the "pai-painter-commercial-base-zh" or "pai/pai-painter-base-zh" or "alibaba-pai/pai-painter-large-zh" for text2image pretrained model weight
alibaba-pai/pai-painter-large-zh: 
`wget https://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/easynlp_modelzoo/alibaba-pai/pai-painter-large-zh.tgz`
alibaba-pai/pai-painter-base-zh:
`wget https://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/easynlp_modelzoo/alibaba-pai/pai-painter-base-zh.tgz`
pai-painter-commercial-base-zh:
`wget https://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/easynlp_modelzoo/alibaba-pai/pai-painter-commercial-base-zh.tgz`
