### ISSUE TITLE
Does EasyNLP have requirements for computer configuration?

### ISSUE THREAD

**Issue by pruidong** [alibaba/EasyNLP#170]
我在VMware中安装了Fedora 36 x64系统,Python 3.7,13GB内存,4核处理器,80GB硬盘.

我看了一篇文章([https://mp.weixin.qq.com/s/Iie7aO-rOMJnynwUSN2hZw](https://mp.weixin.qq.com/s/Iie7aO-rOMJnynwUSN2hZw)),参考文章来进行模型训练,但每次执行模型训练时终端会闪退,我使用top命令监控,发现是内存被耗尽了.请问有处理方式吗?谢谢!

I installed Fedora 36 x64 system in VMware, 13GB RAM, 4 core processor, 80GB HDD.

I read an article (https://mp.weixin.qq.com/s/Iie7aO-rOMJnynwUSN2hZw), refer to the article for model training, but the terminal will flash back every time I execute model training, I use the top command to monitor , It was found that the memory was exhausted. Is there a way to deal with it?thank!

**Comment by chywang** [comment]
py36，GPU建议V100 32G，100GB RAM
