### ISSUE TITLE
Can the processing code for the AST matrix in data preprocessing in SASA be exposed

### ISSUE THREAD

**Issue by hlt0903** [alibaba/EasyNLP#194]
The treatment of AST matrices in the "Understanding Long Programming Languages with Structure-Aware Sparse Attention" is not particularly detailed, and no code is provided. This problem is similar to my current research direction, I hope you can make the code public, thank you very much

**Comment by chywang** [comment]
code available at https://github.com/alibaba/EasyNLP/tree/master/examples/SASA
if you have any questions, consult the first author, thank you
