### ISSUE TITLE
KECP论文代码

### ISSUE THREAD

**Issue by xxmeng20** [alibaba/EasyNLP#209]
你好，没有找到这篇论文的代码。
《KECP: Knowledge Enhanced Contrastive Prompting for Few-shot Extractive Question Answering》

**Comment by chywang** [comment]
@wjn1996 pls add the code to examples/kecp

**Comment by wjn1996** [comment]
@xxmeng20 您好，感谢您的关注，目前该工作在review阶段，accept后会commit，请耐心等待。
