### ISSUE TITLE
easynlp\appzoo\macbert-base-rczh\tokenizer_config.json

### ISSUE THREAD

**Issue by 287955983** [alibaba/EasyNLP#231]
这个文件在哪里，我看下载的模型目录没有这个文件的
![image](https://user-images.githubusercontent.com/92845020/196852050-4b96b70b-761c-40b7-86ca-eb6d307f23f1.png)
![image](https://user-images.githubusercontent.com/92845020/196852087-71194f6e-cdfd-47a7-a233-21b9a99e5e25.png)

**Comment by 287955983** [comment]
https://huggingface.co/hfl/chinese-roberta-wwm-ext/blob/5c58d0b8ec1d9014354d691c538661bf00bfdb44/tokenizer_config.json

**Comment by Chen9154** [comment]
可以贴一下具体的执行语句么？是执行哪几行代码过程中发生了这个报错

**Comment by Chen9154** [comment]
pipeline代码正确调用方式如下，您可以修正下代码中的调用方式，或者更新EasyNLP代码库到最新版本，之后再行尝试：

**Comment by 287955983** [comment]
这个问题我已经解决了，我想做文本匹配的功能，根据网上生成了模型，然后要怎么去使用这个模型，我想弄成接口的形式
