### ISSUE TITLE
这个开发流程吗？生成模型后要怎么应用、想要添加数据要怎么做?

### ISSUE THREAD

**Issue by 287955983** [alibaba/EasyNLP#232]
我生成模型后，想要做一个文字匹配的功能

**Comment by chywang** [comment]
具体任务描述有吗

**Comment by 287955983** [comment]
就是想做一个简单的功能，两句话对比看下意思是否一样

**Comment by chywang** [comment]
https://github.com/alibaba/EasyNLP/tree/master/examples/appzoo_tutorials/text_match/single_tower
