### ISSUE TITLE
SpanProto not found

### ISSUE THREAD

**Issue by Zechen-W** [alibaba/EasyNLP#235]
I see that the paper ***SpanProto: A Two-stage Span-based Prototypical Network for Few-shot Named Entity Recognition*** for **EMNLP 2022** mentions that it will be open sourced in this repository, but I didn't find the specific code. If it is already open source but I didn't find it, where is the specific code? Can you post a link or a tutorial please? If it is not open source yet, when will the author fulfill the promise of open source in the paper? Can you open source it as soon as possible please? This is important for our subsequent work, thanks.

**Comment by chywang** [comment]
@wjn1996 would u pls upload the code asap?

**Comment by wjn1996** [comment]
This code has been committed, it may be under review by easynlp, please wait.

**Comment by chywang** [comment]
https://github.com/alibaba/EasyNLP/tree/master/examples/SpanProto
