### ISSUE TITLE
the code of paper <Understanding Long Programming Languages with Structure-Aware Sparse Attention>

### ISSUE THREAD

**Issue by tom68-ll** [alibaba/EasyNLP#241]
Hi, authors. We are interested in the work of your paper <Understanding Long Programming Languages with Structure-Aware Sparse Attention>. Where can I find the code in EasyNLP? Thank you a lot.

**Comment by chywang** [comment]
https://github.com/alibaba/EasyNLP/tree/master/examples/SASA

**Comment by tom68-ll** [comment]
Thank you a lot!
