### ISSUE TITLE
demo跑不起来啊

### ISSUE THREAD

**Issue by NLPOR** [alibaba/EasyNLP#251]
开源的代码真的能跑吗，缺库
![image](https://user-images.githubusercontent.com/24563120/201597227-a943db1a-b3d9-4f59-88bd-8076c3d1436b.png)
easy_predict 哪来的，找了一圈都没有

还有
ImportError                               Traceback (most recent call last)
Cell In [4], line 2
      1 from easynlp.core import Trainer
----> 2 from easynlp.appzoo import GeneralDataset, SequenceClassification, load_dataset
      3 from easynlp.utils import initialize_easynlp
      5 args = initialize_easynlp()

ImportError: cannot import name 'GeneralDataset' from 'easynlp.appzoo' (unknown location)

是怎么回事啊，还有人维护这个开源仓库吗

**Comment by chywang** [comment]
https://github.com/alibaba/EasyNLP/blob/master/examples/appzoo_tutorials/sequence_classification/bert_classify/run_train_eval_predict_user_defined_local.sh

**Comment by NLPOR** [comment]
这就关了，使用CPU能跑吗，必须使用GPU?

**Comment by chywang** [comment]
基础功能cpu都可以，部分大模型需要gpu
