### ISSUE TITLE
appzoo_tutorial/text_vision 中脚本跑不通

### ISSUE THREAD

**Issue by Chen9154** [alibaba/EasyNLP#252]
[examples](https://github.com/alibaba/EasyNLP/tree/master/examples)/[appzoo_tutorials](https://github.com/alibaba/EasyNLP/tree/master/examples/appzoo_tutorials)/[text_vision](https://github.com/alibaba/EasyNLP/tree/master/examples/appzoo_tutorials/text_vision)/run_train_eval_predict_user_defined_local.sh 脚本跑不通。

train命令行模型名需要更新，predict等命令行缺少必要运行参数。

**Comment by NLPOR** [comment]
很多脚本都跑不通，阿里这开源很敷衍。。。

**Comment by chywang** [comment]
refer to
https://github.com/alibaba/EasyNLP/tree/master/examples/appzoo_tutorials/clip
https://github.com/alibaba/EasyNLP/tree/master/examples/appzoo_tutorials/wukong_clip
