### ISSUE TITLE
请问是否会公开BeautifulPrompt源码？

### ISSUE THREAD

**Issue by nmbtwzt** [alibaba/EasyNLP#326]
您好，感谢您公布了BeautifulPrompt的在线demo，可以让我们在线尝试。很感谢您在这方面做出的努力。
请问是否会公布BeautifulPrompt的训练代码或是数据集？可以让我们自己尝试重新训练。
非常感谢。

**Comment by chywang** [comment]
正在投稿中，论文公开后会提供
