### ISSUE TITLE
model_dir of user's oss checkpoint could not be loaded

### ISSUE THREAD

**Issue by Lin-Youth** [alibaba/EasyNLP#33]
Due to following line of code, user defined model_dir=args.checkpoint_dir could raise RuntimeError "`%s` is not a existing pre-defined model name."

https://github.com/alibaba/EasyNLP/blob/cda9b42358156afed3a0e27173d5e48ef32f0686/easynlp/appzoo/feature_vectorization/predictor.py#L31

Simply comment Line 31 seems to work fine.

**Comment by minghui** [comment]
If the current model_dir is a model name, then this works fine, otherwise needs to remove this. Ideally get_pretrain_model_path() should work for both model name and model path.

**Comment by minghui** [comment]
fixed this issue with this pr: https://github.com/alibaba/EasyNLP/pull/44
