### ISSUE TITLE
脚本里的export CUDA_VISIBLE_DEVICES不起作用

### ISSUE THREAD

**Issue by wjn1996** [alibaba/EasyNLP#35]
脚本里的export CUDA_VISIBLE_DEVICES不起作用，main函数里的os.environ["CUDA_VISIBLE_DEVICES"] = "1"也没有作用，不论设置多少值都会默认在0号卡上运行。
不知道是不是bug

**Comment by minghui** [comment]
哪个脚本？

**Comment by wjn1996** [comment]
已解决
