### ISSUE TITLE
No module named 'easy_predict'

### ISSUE THREAD

**Issue by wonius** [alibaba/EasyNLP#71]
当运行 main.py 时，报错找不到 easy_predict 模块：

/usr/bin/python3 /Users/gavin/Downloads/PycharmProjects/EasyNLP/EasyNLP/examples/quick_start/main.py
No module named 'easy_predict'
Traceback (most recent call last):
  File "/Users/gavin/Downloads/PycharmProjects/EasyNLP/EasyNLP/examples/quick_start/main.py", line 5, in <module>
    args = initialize_easynlp()
  File "/Users/gavin/Downloads/PycharmProjects/EasyNLP/EasyNLP/easynlp/utils/initializer.py", line 34, in initialize_easynlp
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/Users/gavin/Downloads/PycharmProjects/EasyNLP/EasyNLP/easynlp/utils/global_vars.py", line 144, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/Users/gavin/Downloads/PycharmProjects/EasyNLP/EasyNLP/easynlp/utils/global_vars.py", line 204, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/Users/gavin/Downloads/PycharmProjects/EasyNLP/EasyNLP/easynlp/utils/arguments.py", line 70, in parse_args
    assert args.tables is not None
AssertionError

环境：
$ python -V
Python 3.8.9

$ pip list
Package                 Version
----------------------- -----------
absl-py                 1.0.0
beautifulsoup4          4.11.1
bs4                     0.0.1
cachetools              5.0.0
certifi                 2021.10.8
charset-normalizer      2.0.12
click                   8.1.2
cycler                  0.11.0
filelock                3.6.0
fonttools               4.33.2
google-auth             2.6.6
google-auth-oauthlib    0.4.6
grpcio                  1.45.0
idna                    3.3
importlib-metadata      4.5.0
jieba                   0.42.1
joblib                  1.1.0
kiwisolver              1.4.2
lxml                    4.8.0
Markdown                3.3.6
matplotlib              3.5.1
nltk                    3.7
numpy                   1.22.3
oauthlib                3.2.0
opencv-python           4.5.5.64
packaging               21.3
pandas                  1.4.2
pandas-datareader       0.10.0
Pillow                  9.1.0
pip                     22.0.4
protobuf                3.20.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyparsing               3.0.8
python-dateutil         2.8.2
pytz                    2022.1
regex                   2022.4.24
requests                2.27.1
requests-oauthlib       1.3.1
rouge                   1.0.1
rsa                     4.8
sacremoses              0.0.49
scikit-learn            1.0.2
scipy                   1.8.0
sentencepiece           0.1.96
setuptools              62.1.0
six                     1.16.0
soupsieve               2.3.2.post1
tensorboard             2.9.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorboardX            2.5
threadpoolctl           3.1.0
tokenizers              0.10.1
torch                   1.9.0
torchvision             0.12.0
tqdm                    4.64.0
typing_extensions       4.2.0
urllib3                 1.26.9
Werkzeug                2.1.2
wheel                   0.33.1
zipp                    3.8.0

Process finished with exit code 1

**Comment by minghui** [comment]
这个报错的正常的  只是一个warning 没有关系
你的问题是这个：assert args.tables is not None
默认tables放的是输入的数据，你应该是没有配置输入。具体可以参考这个例子：https://github.com/alibaba/EasyNLP/blob/master/examples/quick_start_user_defined/run_user_defined_local.sh

**Comment by wonius** [comment]
执行shell 脚本，报错：

$ sh run_user_defined_local.sh
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from easynlp.core import Trainer
ImportError: No module named easynlp.core

requirements 都已经下载完了。我用的 pycharm，也能识别这么模块。
我看easynlp 目录下的__init__.py 内容是空的，会不会跟这个有关？
