### ISSUE TITLE
Dataset about Meta-KD

### ISSUE THREAD

**Issue by wpwpwpyo** [alibaba/EasyNLP#76]
The datasets of 'https://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/datasets/domain_data/domain_sentiment_data.tar.gz
  tar -zxvf domain_sentiment_data.tar.gz' in the the path of 'examples/knowledge_distillation/run_meta_preprocess.sh' line 16 can't download now.Could you please provide a download method?

**Comment by minghui** [comment]
please use this new address instead: http://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/datasets/domain_sentiment_data.tar.gz

**Comment by wpwpwpyo** [comment]
> 

Sorry to bother you again.After downloading from the new address 'http://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/datasets/domain_sentiment_data.tar.gz',it shows 'The compressed file is corrupted' and only with 148KB size.So I can't run 'tar -zxvf domain_sentiment_data.tar.gz'

**Comment by minghui** [comment]
Thanks  for pointing out the problem. I've uploaded a new tar file. Pls re-download the dataset.
