### ISSUE TITLE
New Datasets about Meta-KD

### ISSUE THREAD

**Issue by wpwpwpyo** [alibaba/EasyNLP#79]
Sorry to bother you again.After downloading from the new address 'http://atp-modelzoo-sh.oss-cn-shanghai.aliyuncs.com/release/datasets/domain_sentiment_data.tar.gz' in the the path of 'examples/knowledge_distillation/run_meta_preprocess.sh' line 16. it shows 'The compressed file is corrupted' and only with 148KB size.So I can't run 'tar -zxvf domain_sentiment_data.tar.gz'

**Comment by minghui** [comment]
Thanks  for pointing out the problem. I've uploaded a new tar file. pls double check~
