### ISSUE TITLE
Some question about Meta-KD

### ISSUE THREAD

**Issue by wpwpwpyo** [alibaba/EasyNLP#80]
Sorry to bother you.When I run the 'bash ﻿examples/knowledge_distillation/meta_student_distill.sh' , the logs shows below:
![图片](https://user-images.githubusercontent.com/49509792/167618306-95b15817-e795-4e7b-83b5-e3d17377eb3f.png)
Is this a version of easynlp promblem?I already run the '﻿pip install pai-easynlp' according to ﻿https://github.com/alibaba/EasyNLP readme.md.And I try ﻿:
$ git clone https://github.com/alibaba/EasyNLP.git
$ cd EasyNLP
$ python setup.py install
it failed because:
![图片](https://user-images.githubusercontent.com/49509792/167618861-42dc75f9-cc46-496b-a8f1-36836706f049.png)

**Comment by Longpai** [comment]
Thank you first for your issue, the namespace of args has no attribute 'use_torchxla', the correct attribute is 'use_torchacc'. The commit to fix this bug has been submitted.

**Comment by minghui** [comment]
This issue can be solved by this pr: https://github.com/alibaba/EasyNLP/pull/81
